SDL_BASE = /usr/bin/
include $(PWD)/steam_rules

CFLAGS := `$(SDL_BASE)sdl-config --cflags` -O3 -DCPP_MEMORY -Wall -I/usr/local/include \
-I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__ -D_NO_JACK_ -D_NDEBUG

CXXFLAGS:= $(CFLAGS)

EXTENSION:= steam-exe

LIBS    :=  -O3 -L/local/lib -Wl,-rpath,/usr/local/lib -lasound -lSDL -ljack -lpthread